/^#define NCURSES/!s/NCURSES_SP_DCLx/SCREEN *NCURSES_SP_ARGx/g
/^#define NCURSES/!s/NCURSES_SP_ARGx/NCURSES_SP_ARG,/g
/^#define NCURSES/!s/NCURSES_SP_DCL0/NCURSES_SP_DCL/g
/^#define NCURSES/!s/NCURSES_SP_DCL/SCREEN *NCURSES_SP_ARG/g
/^#define NCURSES/!s/NCURSES_SP_ARG/SP_PARM/g
s/SP_PARM/sp/g
