/^#define NCURSES_SP_DCLx/!s/NCURSES_SP_DCLx/SCREEN *NCURSES_SP_ARGx/g
/^#define NCURSES_SP_ARGx/!s/NCURSES_SP_ARGx/NCURSES_SP_ARG,/g
/^#define NCURSES_SP_DCL0/!s/NCURSES_SP_DCL0/NCURSES_SP_DCL/g
/^#define NCURSES_SP_DCL/!s/NCURSES_SP_DCL/SCREEN *NCURSES_SP_ARG/g
/^#define NCURSES_SP_ARG/!s/NCURSES_SP_ARG/SP_PARM/g
/^#define SP_PARM/!s/SP_PARM/sp/g
